"""
forgepilot_sdk

Python implementation aligned with @codeany/open-agent-sdk-typescript.
"""

from forgepilot_sdk.agent import Agent, createAgent, create_agent, query
from forgepilot_sdk.engine import QueryEngine
from forgepilot_sdk.hooks import (
    HOOK_EVENTS,
    HookConfig,
    HookDefinition,
    HookEvent,
    HookInput,
    HookOutput,
    HookRegistry,
    createHookRegistry,
    create_hook_registry,
)
from forgepilot_sdk.mcp import (
    MCPConnection,
    closeAllConnections,
    close_all_connections,
    connectMCPServer,
    connect_mcp_server,
)
from forgepilot_sdk.providers import (
    AnthropicMessagesProvider,
    AnthropicProvider,
    OpenAICompatibleProvider,
    OpenAIProvider,
    createProvider,
    create_provider,
)
from forgepilot_sdk.sdk_mcp_server import (
    McpSdkServerConfig,
    createSdkMcpServer,
    create_sdk_mcp_server,
    isSdkServerConfig,
    is_sdk_server_config,
)
from forgepilot_sdk.session import (
    appendToSession,
    append_to_session,
    deleteSession,
    delete_session,
    forkSession,
    fork_session,
    getSessionInfo,
    getSessionMessages,
    get_session_info,
    get_session_messages,
    listSessions,
    list_sessions,
    loadSession,
    load_session,
    renameSession,
    rename_session,
    saveSession,
    save_session,
    tagSession,
    tag_session,
)
from forgepilot_sdk.skills import (
    clearSkills,
    clear_skills,
    formatSkillsForPrompt,
    format_skills_for_prompt,
    getAllSkills,
    getSkill,
    getUserInvocableSkills,
    get_all_skills,
    get_skill,
    get_user_invocable_skills,
    hasSkill,
    has_skill,
    initBundledSkills,
    init_bundled_skills,
    load_default_skill_registry,
    load_skill_registry_from_paths,
    load_skills_from_dir,
    registerSkill,
    register_skill,
    unregisterSkill,
    unregister_skill,
)
from forgepilot_sdk.tool_helper import (
    CallToolResult,
    SdkMcpToolDefinition,
    ToolAnnotations,
    sdkToolToToolDefinition,
    sdk_tool_to_tool_definition,
    tool,
)
import forgepilot_sdk.tools as _tools
import forgepilot_sdk.types as _types
import forgepilot_sdk.providers.base as _provider_types
from forgepilot_sdk.tools import (
    assembleToolPool,
    assemble_tool_pool,
    clear_agents,
    clear_config,
    clear_cron_jobs,
    clear_mailboxes,
    clear_question_handler,
    clear_tasks,
    clear_teams,
    clear_todos,
    defineTool,
    define_tool,
    filterTools,
    filter_tools,
    getAllBaseTools,
    get_all_base_tools,
    get_all_cron_jobs,
    get_all_tasks,
    get_all_teams,
    get_config,
    get_current_plan,
    get_task,
    get_team,
    get_todos,
    is_plan_mode_active,
    read_mailbox,
    register_agents,
    set_config,
    set_deferred_tools,
    set_mcp_connections,
    set_question_handler,
    toApiTool,
    to_api_tool,
    write_to_mailbox,
)
from forgepilot_sdk.types import (
    AgentOptions,
    ConversationMessage,
    QueryRequest,
    QueryResult,
    SDKMessage,
    ThinkingConfig,
    ToolContext,
    ToolDefinition,
    ToolResult,
)
from forgepilot_sdk.utils import *  # noqa: F401,F403
from forgepilot_sdk.utils import __all__ as _utils_all

__all__ = [
    "Agent",
    "create_agent",
    "createAgent",
    "query",
    "QueryEngine",
    "AgentOptions",
    "QueryRequest",
    "QueryResult",
    "SDKMessage",
    "ConversationMessage",
    "ThinkingConfig",
    "ToolDefinition",
    "ToolContext",
    "ToolResult",
    "tool",
    "sdkToolToToolDefinition",
    "sdk_tool_to_tool_definition",
    "SdkMcpToolDefinition",
    "ToolAnnotations",
    "CallToolResult",
    "create_sdk_mcp_server",
    "createSdkMcpServer",
    "is_sdk_server_config",
    "isSdkServerConfig",
    "McpSdkServerConfig",
    "create_provider",
    "createProvider",
    "AnthropicMessagesProvider",
    "OpenAICompatibleProvider",
    "AnthropicProvider",
    "OpenAIProvider",
    "define_tool",
    "defineTool",
    "to_api_tool",
    "toApiTool",
    "get_all_base_tools",
    "getAllBaseTools",
    "filter_tools",
    "filterTools",
    "assemble_tool_pool",
    "assembleToolPool",
    "register_agents",
    "clear_agents",
    "read_mailbox",
    "write_to_mailbox",
    "clear_mailboxes",
    "get_all_tasks",
    "get_task",
    "clear_tasks",
    "get_all_teams",
    "get_team",
    "clear_teams",
    "is_plan_mode_active",
    "get_current_plan",
    "set_question_handler",
    "clear_question_handler",
    "set_deferred_tools",
    "set_mcp_connections",
    "get_all_cron_jobs",
    "clear_cron_jobs",
    "get_config",
    "set_config",
    "clear_config",
    "get_todos",
    "clear_todos",
    "connect_mcp_server",
    "connectMCPServer",
    "close_all_connections",
    "closeAllConnections",
    "MCPConnection",
    "save_session",
    "load_session",
    "list_sessions",
    "fork_session",
    "append_to_session",
    "delete_session",
    "get_session_messages",
    "get_session_info",
    "rename_session",
    "tag_session",
    "saveSession",
    "loadSession",
    "listSessions",
    "forkSession",
    "appendToSession",
    "deleteSession",
    "getSessionMessages",
    "getSessionInfo",
    "renameSession",
    "tagSession",
    "load_default_skill_registry",
    "load_skill_registry_from_paths",
    "load_skills_from_dir",
    "register_skill",
    "get_skill",
    "get_all_skills",
    "get_user_invocable_skills",
    "has_skill",
    "unregister_skill",
    "clear_skills",
    "format_skills_for_prompt",
    "registerSkill",
    "getSkill",
    "getAllSkills",
    "getUserInvocableSkills",
    "hasSkill",
    "unregisterSkill",
    "clearSkills",
    "formatSkillsForPrompt",
    "init_bundled_skills",
    "initBundledSkills",
    "HookRegistry",
    "HookDefinition",
    "HookConfig",
    "HookEvent",
    "HookInput",
    "HookOutput",
    "create_hook_registry",
    "createHookRegistry",
    "HOOK_EVENTS",
]

__all__.extend([name for name in _utils_all if name not in __all__])

_UPSTREAM_TOOL_EXPORTS = [
    "BashTool",
    "FileReadTool",
    "FileWriteTool",
    "FileEditTool",
    "GlobTool",
    "GrepTool",
    "NotebookEditTool",
    "WebFetchTool",
    "WebSearchTool",
    "AgentTool",
    "SendMessageTool",
    "TeamCreateTool",
    "TeamDeleteTool",
    "TaskCreateTool",
    "TaskListTool",
    "TaskUpdateTool",
    "TaskGetTool",
    "TaskStopTool",
    "TaskOutputTool",
    "EnterWorktreeTool",
    "ExitWorktreeTool",
    "EnterPlanModeTool",
    "ExitPlanModeTool",
    "AskUserQuestionTool",
    "ToolSearchTool",
    "ListMcpResourcesTool",
    "ReadMcpResourceTool",
    "CronCreateTool",
    "CronDeleteTool",
    "CronListTool",
    "RemoteTriggerTool",
    "LSPTool",
    "ConfigTool",
    "TodoWriteTool",
    "SkillTool",
    "registerAgents",
    "clearAgents",
    "readMailbox",
    "writeToMailbox",
    "clearMailboxes",
    "getAllTasks",
    "getTask",
    "clearTasks",
    "getAllTeams",
    "getTeam",
    "clearTeams",
    "isPlanModeActive",
    "getCurrentPlan",
    "setQuestionHandler",
    "clearQuestionHandler",
    "setDeferredTools",
    "setMcpConnections",
    "getAllCronJobs",
    "clearCronJobs",
    "getConfig",
    "setConfig",
    "clearConfig",
    "getTodos",
    "clearTodos",
]
for _name in _UPSTREAM_TOOL_EXPORTS:
    if _name not in globals() and hasattr(_tools, _name):
        globals()[_name] = getattr(_tools, _name)
    if _name not in __all__:
        __all__.append(_name)

if "sdkToolToToolDefinition" not in __all__:
    __all__.append("sdkToolToToolDefinition")

_UPSTREAM_TYPE_EXPORTS = [
    "AgentDefinition",
    "AgentMessage",
    "ApiType",
    "AssistantMessage",
    "CanUseToolFn",
    "CanUseToolResult",
    "ContentBlock",
    "ContentBlockParam",
    "CreateMessageParams",
    "CreateMessageResponse",
    "CronJob",
    "HookConfig",
    "HookEvent",
    "HookInput",
    "HookOutput",
    "LLMProvider",
    "McpHttpConfig",
    "McpServerConfig",
    "McpSseConfig",
    "McpStdioConfig",
    "Message",
    "MessageRole",
    "ModelInfo",
    "NormalizedContentBlock",
    "NormalizedMessageParam",
    "NormalizedResponseBlock",
    "NormalizedTool",
    "OutputFormat",
    "PermissionBehavior",
    "PermissionMode",
    "QueryEngineConfig",
    "RetryConfig",
    "SDKAssistantMessage",
    "SDKPartialMessage",
    "SDKResultMessage",
    "SDKToolResultMessage",
    "SandboxFilesystemConfig",
    "SandboxNetworkConfig",
    "SandboxSettings",
    "SessionData",
    "SessionMetadata",
    "SettingSource",
    "SkillContentBlock",
    "SkillDefinition",
    "SkillResult",
    "Task",
    "TaskStatus",
    "Team",
    "TodoItem",
    "TokenUsage",
    "ToolInputSchema",
    "UserMessage",
]
for _name in _UPSTREAM_TYPE_EXPORTS:
    if _name in globals():
        if _name not in __all__:
            __all__.append(_name)
        continue
    if hasattr(_types, _name):
        globals()[_name] = getattr(_types, _name)
    elif hasattr(_provider_types, _name):
        globals()[_name] = getattr(_provider_types, _name)
    if _name in globals() and _name not in __all__:
        __all__.append(_name)
